Repository ummgoban/client-app, pull requests merged in 2024-10, with the labels that each got.

#58 feat: 테마 적용
  src/context/theme.ts
Labels: feature

#59 feat: 마이페이지 제작 및 주문 내역 분리
  src/components/common/ListBox.style.tsx
  src/components/common/ListBox.tsx
  src/components/common/NavigateTextButton.style.tsx
  src/components/common/NavigateTextButton.tsx
  src/components/common/TabBar.tsx
  src/components/myPage/Profile.style.tsx
  src/components/myPage/Profile.tsx
  src/components/myPage/index.ts
  src/components/orderHistory/HistoryTimeline.style.tsx
  src/components/orderHistory/HistoryTimeline.tsx
  src/components/orderHistory/OrderHistory.style.tsx
  src/components/orderHistory/OrderHistory.tsx
  src/navigation/HomeNavigator.tsx
  src/screens/MyPageScreen/UserMyPage.style.tsx
  src/screens/MyPageScreen/UserMyPage.tsx
  src/screens/MyPageScreen/index.tsx
  src/screens/OrderHistoryScreen/OrderHistory.style.tsx
  src/screens/OrderHistoryScreen/index.tsx
  src/types/StackNavigationType.ts
Labels: feature

#61 feat: 픽업 예약 시간 설정
  __tests__/utils/date.test.ts
  package.json
  src/components/common/DatePicker.style.tsx
  src/components/common/DatePicker.tsx
  src/components/feedPage/Market.tsx
  src/components/orderHistory/HistoryTimeline.tsx
  src/components/orderHistory/OrderHistory.tsx
  src/components/orderPage/DatePickerCard.style.tsx
  src/components/orderPage/DatePickerCard.tsx
  src/screens/MarketDetailScreen/MarketDetailPage.tsx
  src/screens/PaymentScreen/PaymentPage.tsx
  src/utils/date.ts
  yarn.lock
Labels: feature, view

#66 feat: 가게 이름을 헤더에 표시
  src/screens/MarketDetailScreen/index.tsx
Labels: enhancement
