Repository ummgoban/client-app, pull requests merged in 2025-03, with the labels that each got.

#149 feat: react query migration - auth
  App.tsx
  src/apis/Login.ts
  src/apis/Market.ts
  src/apis/User.ts
  src/apis/auth/client.ts
  src/apis/auth/index.ts
  src/apis/auth/model.ts
  src/apis/auth/oauthHelper.ts
  src/apis/auth/query.ts
  src/apis/index.ts
  src/apis/markets/query.ts
  src/components/LoginPage/CredentialLogin.tsx
  src/components/LoginPage/CredentialSignUp.tsx
  src/components/common/SubscribeIcon.tsx
  src/hooks/useProfile.ts
  src/screens/MyPageScreen/UserMyPage.tsx
  src/screens/MyPageScreen/index.tsx
  src/screens/RegisterScreen/LoginScreen.tsx
Labels: feature

#150 feat: react-query migration - buckets
  src/apis/buckets/client.ts
  src/apis/buckets/index.ts
  src/apis/buckets/model.ts
  src/apis/buckets/query.ts
  src/components/marketDetailPage/Menu.tsx
  src/screens/MarketDetailScreen/MarketDetailPage.tsx
  src/screens/PaymentScreen/index.tsx
  src/screens/ShoppingCartScreen/ShoppingCartPage.tsx
  src/screens/ShoppingCartScreen/index.tsx
Labels: feature

#156 ci: actions cache version up
  .github/workflows/lint.yml
Labels: dependencies

#157 feat: 페이지네이션 api 수정, header 통일
  src/apis/auth/client.ts
  src/apis/markets/client.ts
  src/apis/markets/model.ts
  src/apis/markets/query.ts
  src/components/common/Appbar/HeaderTitle.style.tsx
  src/components/common/Appbar/HeaderTitle.tsx
  src/components/common/EmptyComponent/EmptyComponent.style.tsx
  src/components/common/EmptyComponent/EmptyComponent.tsx
  src/components/common/EmptyComponent/index.ts
  src/components/common/FeedBottomFloatingButton/FeedBottomFloatingButton.style.tsx
  src/components/common/FeedBottomFloatingButton/FeedBottomFloatingButton.tsx
  src/components/common/FeedBottomFloatingButton/index.ts
  src/components/common/HeaderTitle.style.tsx
  src/components/map/MyLocationMap.style.tsx
  src/components/map/MyLocationMap.tsx
  src/components/orderDetail/OrderDescription.tsx
  src/context/ReactQueryProvider.tsx
  src/hooks/useGPSLocation.tsx
  src/navigation/CartNavigator.tsx
  src/navigation/DetailNavigator.tsx
  src/navigation/FeedNavigator.tsx
  src/navigation/HomeNavigator.tsx
  src/screens/FeedScreen/Feed.style.tsx
  src/screens/FeedScreen/index.tsx
  src/screens/MapScreen/MapScreen.style.tsx
  src/screens/MapScreen/index.tsx
  src/screens/MarketDetailScreen/MarketDetailPage.tsx
  src/screens/MarketDetailScreen/index.tsx
  src/screens/MarketScreen.tsx
  src/screens/MyPageScreen/NonMemberMyPage.style.tsx
  src/screens/MyPageScreen/NonMemberMyPage.tsx
  src/screens/MyPageScreen/index.tsx
  src/screens/OrderHistoryScreen/index.tsx
  src/screens/PaymentScreen/PaymentPage.tsx
  src/screens/PaymentScreen/index.tsx
  src/screens/ShoppingCartScreen/EmptyCartPage.style.tsx
  src/screens/ShoppingCartScreen/EmptyCartPage.tsx
  src/screens/ShoppingCartScreen/ShoppingCartPage.tsx
  src/screens/ShoppingCartScreen/index.tsx
  src/screens/SubscribeScreen/index.tsx
  src/types/StackNavigationType.ts
Labels: enhancement

#160 feat: 에러헨들링 코드 작성합니다.
  src/apis/ApiClient.ts
  src/apis/CustomError.ts
  src/apis/auth/client.ts
  src/apis/auth/query.ts
  src/apis/buckets/client.ts
  src/apis/markets/client.ts
  src/apis/markets/query.ts
  src/apis/orders/client.ts
  src/apis/review/client.ts
  src/components/LoginPage/CredentialLogin.tsx
  src/hooks/useProfile.ts
  src/screens/MyPageScreen/UserMyPage.tsx
Labels: enhancement

#165 fix: change safearea to useSafeAreaInsets
  App.tsx
  src/navigation/Layout.style.tsx
  src/navigation/index.tsx
Labels: bug

#166 feat: 회원가입 이메일 인증 로직 구현
  src/apis/ApiClient.ts
  src/apis/auth/client.ts
  src/apis/auth/model.ts
  src/apis/auth/query.ts
  src/components/LoginPage/CredentialLogin.style.tsx
  src/components/LoginPage/CredentialSignUp.tsx
  src/components/common/TextInput/TextInput.tsx
  src/hooks/useProfile.ts
  src/screens/MarketDetailScreen/MarketDetail.style.tsx
Labels: feature

#171 fix: safeArea 적용 및 그에 따른 디자인 변경
  App.tsx
  ios/Podfile.lock
  src/components/common/BottomButton.style.tsx
  src/components/common/EmptyComponent/EmptyComponent.style.tsx
  src/components/common/ListBox.style.tsx
  src/components/common/SubscribeIcon.tsx
  src/components/common/TabBar.tsx
  src/components/subscribePage/SubscribeMarketCard.style.tsx
  src/navigation/CartNavigator.tsx
  src/navigation/DetailNavigator.tsx
  src/navigation/MyPageNavigator.tsx
  src/navigation/index.tsx
  src/screens/FeedScreen/Feed.style.tsx
  src/screens/MarketDetailScreen/MarketDetail.style.tsx
  src/screens/MyPageScreen/NoticePage.style.tsx
  src/screens/MyPageScreen/UserMyPage.style.tsx
  src/screens/OrderDoneScreen/OrderDoneScreen.style.tsx
  src/screens/OrderDoneScreen/index.tsx
  src/screens/OrderHistoryScreen/OrderHistory.style.tsx
  src/screens/PaymentScreen/PaymentPage.style.tsx
  src/screens/SettingScreen/SettingScreen.style.tsx
  src/screens/ShoppingCartScreen/ShoppingCartPage.style.tsx
  src/screens/SubscribeScreen/SubscribeScreen.style.tsx
Labels: enhancement

#176 feat: 고객 리뷰 페이지 구현
  android/app/src/main/AndroidManifest.xml
  ios/ClientApp/Info.plist
  ios/ClientApp/PrivacyInfo.xcprivacy
  ios/Podfile.lock
  package.json
  src/components/orderHistory/OrderHistory.style.tsx
  src/components/orderHistory/OrderHistory.tsx
  src/components/review/RaitingStarts.style.tsx
  src/components/review/RatingStarts.tsx
  src/components/review/UploadedPicture.style.tsx
  src/components/review/UplodedPicture.tsx
  src/navigation/DetailNavigator.tsx
  src/screens/ReviewScreen/ReviewScreen.style.tsx
  src/screens/ReviewScreen/index.tsx
  src/types/OrderType.ts
  src/types/StackNavigationType.ts
  src/utils/image-picker.ts
  yarn.lock
Labels: feature

#182 feat: 가게별 리뷰 조회 페이지 구현
  src/apis/review/client.ts
  src/apis/review/model.ts
  src/components/common/CustomImageModal.tsx
  src/components/common/SubscribeIcon.tsx
  src/components/marketReview/MarketReviewCard.style.tsx
  src/components/marketReview/MarketReviewCard.tsx
  src/components/marketReview/index.ts
  src/components/orderHistory/OrderHistory.tsx
  src/components/reviewCreate/RaitingStarts.style.tsx
  src/components/reviewCreate/RatingStarts.tsx
  src/components/reviewCreate/UploadedPicture.style.tsx
  src/components/reviewCreate/UplodedPicture.tsx
  src/navigation/DetailNavigator.tsx
  src/screens/MarketDetailScreen/MarketDetail.style.tsx
  src/screens/MarketDetailScreen/MarketDetailPage.tsx
  src/screens/MarketDetailScreen/index.tsx
  src/screens/MarketReviewScreen/MarketReviewScreen.style.tsx
  src/screens/MarketReviewScreen/index.tsx
  src/screens/ReviewCreateScreen/ReviewCreateScreen.style.tsx
  src/screens/ReviewCreateScreen/index.tsx
  src/types/Market.ts
  src/types/Review.ts
  src/types/StackNavigationType.ts
Labels: feature

#184 release: v1.0.0
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/ClientApp.xcodeproj/project.pbxproj
  ios/ClientApp/Info.plist
  package.json
  src/apis/auth/client.ts
  src/apis/auth/query.ts
  src/hooks/useProfile.ts
  src/navigation/MyPageNavigator.tsx
  src/screens/MyPageScreen/NicknamePatchPage.tsx
  src/screens/MyPageScreen/NoticePage.style.tsx
  src/screens/MyPageScreen/NoticePage.tsx
  src/screens/MyPageScreen/PolicyPage.tsx
  src/screens/MyPageScreen/UserMyPage.style.tsx
  src/screens/MyPageScreen/UserMyPage.tsx
  src/screens/RegisterScreen/LoginScreen.tsx
  src/types/StackNavigationType.ts
Labels: release
